import type { Mission } from "@/types/database";

/**
 * Static mock data for development.
 * Covers all 5 statuses, various priorities, and multiple assignee types.
 */
export const MOCK_MISSIONS: Mission[] = [
  {
    id: "m-001",
    goal_id: null,
    title: "Design database schema for auth module",
    description: "Create PostgreSQL schema for user authentication including sessions, tokens, and rate limiting.",
    priority: 0,
    assignee_type: "human",
    status: "completed",
    input_context_id: null,
    output_context_id: "ctx-001",
    version: 3,
    created_at: "2026-03-05T10:00:00Z",
    updated_at: "2026-03-05T18:30:00Z",
  },
  {
    id: "m-002",
    goal_id: null,
    title: "Implement Edge Function for mission claiming",
    description: "Build the Supabase Edge Function that handles atomic mission claim with SKIP LOCKED.",
    priority: 0,
    assignee_type: "agent_claude",
    status: "in_progress",
    input_context_id: "ctx-001",
    output_context_id: null,
    version: 2,
    created_at: "2026-03-05T14:00:00Z",
    updated_at: "2026-03-06T09:15:00Z",
  },
  {
    id: "m-003",
    goal_id: null,
    title: "Write unit tests for token ledger service",
    description: "Cover idempotency, cost calculation, and aggregation queries.",
    priority: 1,
    assignee_type: "agent_cursor",
    status: "reviewing",
    input_context_id: null,
    output_context_id: "ctx-003",
    version: 2,
    created_at: "2026-03-05T16:00:00Z",
    updated_at: "2026-03-06T08:00:00Z",
  },
  {
    id: "m-004",
    goal_id: null,
    title: "Set up CI/CD pipeline with GitHub Actions",
    description: "Configure build, lint, type-check, and deploy workflows.",
    priority: 2,
    assignee_type: "none",
    status: "todo",
    input_context_id: null,
    output_context_id: null,
    version: 1,
    created_at: "2026-03-06T08:00:00Z",
    updated_at: "2026-03-06T08:00:00Z",
  },
  {
    id: "m-005",
    goal_id: null,
    title: "Create API route for context CRUD",
    description: "Next.js API routes for creating, reading, and updating context documents.",
    priority: 1,
    assignee_type: "agent_claude",
    status: "todo",
    input_context_id: "ctx-001",
    output_context_id: null,
    version: 1,
    created_at: "2026-03-06T09:00:00Z",
    updated_at: "2026-03-06T09:00:00Z",
  },
  {
    id: "m-006",
    goal_id: null,
    title: "Integrate Supabase Auth with middleware",
    description: "Add Next.js middleware for session refresh and route protection.",
    priority: 1,
    assignee_type: "human",
    status: "in_progress",
    input_context_id: null,
    output_context_id: null,
    version: 2,
    created_at: "2026-03-05T12:00:00Z",
    updated_at: "2026-03-06T10:00:00Z",
  },
  {
    id: "m-007",
    goal_id: null,
    title: "Build token cost dashboard components",
    description: "Visualize per-agent and per-mission cost breakdown.",
    priority: 2,
    assignee_type: "none",
    status: "todo",
    input_context_id: null,
    output_context_id: null,
    version: 1,
    created_at: "2026-03-06T10:00:00Z",
    updated_at: "2026-03-06T10:00:00Z",
  },
  {
    id: "m-008",
    goal_id: null,
    title: "Optimize RLS policies for mission queries",
    description: "Benchmark and improve RLS performance using (select auth.role()) pattern.",
    priority: 2,
    assignee_type: "agent_script",
    status: "completed",
    input_context_id: null,
    output_context_id: "ctx-008",
    version: 4,
    created_at: "2026-03-04T08:00:00Z",
    updated_at: "2026-03-05T14:00:00Z",
  },
  {
    id: "m-009",
    goal_id: null,
    title: "Fix version conflict in concurrent claim",
    description: "Race condition when two agents claim the same mission simultaneously.",
    priority: 0,
    assignee_type: "agent_claude",
    status: "failed",
    input_context_id: "ctx-009",
    output_context_id: null,
    version: 3,
    created_at: "2026-03-05T09:00:00Z",
    updated_at: "2026-03-05T15:00:00Z",
  },
  {
    id: "m-010",
    goal_id: null,
    title: "Document Context Flow architecture",
    description: "Write comprehensive docs on input/output context pipeline for onboarding.",
    priority: 3,
    assignee_type: "human",
    status: "reviewing",
    input_context_id: null,
    output_context_id: "ctx-010",
    version: 2,
    created_at: "2026-03-05T11:00:00Z",
    updated_at: "2026-03-06T07:00:00Z",
  },
];

/** Get all mock missions (simulates async DB call). */
export async function getMockMissions(): Promise<Mission[]> {
  return MOCK_MISSIONS;
}
